Edit message function using jqurey
fukumotomasashi/chat-space pull request #5
Opened 2019-01-12 09:29 UTC by fukumotomasashi

# What
  chat-spaceのメッセージ投稿機能で非同期通信を実装

# Why
 非同期通信を実装することで、メッセージを送信するごとに
ビュー全体が更新されることなくメッセージを表記する部分だけが変更できるようになる。
そうすることでユーザーにとってストレスのないビューになるため。

2019-01-12 09:45 UTC, takebn26 requested changes

2019-01-12 09:45 UTC, takebn26 commented on app/assets/javascripts/massage.js
> +          var html = (message.image !== null)?
【IMO】三項演算子を使おうとしているのとてもいいですね
?前に半角スペースがあるとよりわかりやすいです。
また、
```
<img class="massage-image" src="${ message.image }" alt="${ message.image }">
```
条件文によって上記のコードのあるなしだけだと思うので、
DRYを考えて必要最小限の内容にしてみましょう

2019-01-12 09:45 UTC, takebn26 commented on app/views/massages/create.json.jbuilder
> +
【IMO】空行は１行がいいですね

2019-01-12 09:45 UTC, takebn26 commented on app/assets/javascripts/massage.js
> +    $('.content-body').animate({scrollTop: $('.content-body')[0].scrollHeight}, 'fast');
【IMO】ここにスクロール入れてしまうと、成功して、メッセージが増えた後にスクロールが起きない気がしますね

2019-01-12 09:45 UTC, takebn26 commented on app/views/massages/create.json.jbuilder
> +json.created_at @massage.created_at.strftime("%Y/%m/%d %H:%M")
【IMO】こちらのcreated_at.strftimeメソッドをhelperメソッドに定義してみましょう
date_formatできるとなおいいですね

2019-01-13 08:42 UTC, fukumotomasashi commented
修正しました

2019-01-13 08:45 UTC, kuroko918 commented
LGTMです！

2019-01-13 08:48 UTC, merged