Add incremental search to user
fukumotomasashi/chat-space pull request #6
Opened 2019-01-15 11:51 UTC by fukumotomasashi

# What
グループの新規作成、編集時に追加するチャットメンバーを検索するインクリメンタルサーチの実装。

# Why
インクリメンタルサーチを実装することにより、チャットメンバーの検索をする時にユーザーにとって負担のかからないビューにするため。

2019-01-15 11:57 UTC, ghost requested changes

2019-01-15 11:57 UTC, hiroki5123 commented on app/assets/javascripts/user.js
> +  var add_user_list = $('#user-search-result')
スネークケースとキャメルケースが混ざって存在しているので、キャメルケースに統一しましょう！

2019-01-15 11:57 UTC, hiroki5123 commented on app/assets/javascripts/user.js
> +          appendUser(user);
インデント一個奥です

2019-01-15 11:57 UTC, hiroki5123 commented on app/controllers/users_controller.rb
> +      format.html
これ必要でしょうか？

2019-01-15 11:57 UTC, hiroki5123 commented on app/assets/javascripts/user.js
> +        appendUser2(user)
appendUser2っていうメソッド名は適切ではない気がします

2019-01-15 12:24 UTC, fukumotomasashi commented on app/controllers/users_controller.rb
> +      format.html
これと言うのは４行とも全てでしょうか？
４行ともであれば必要だと思います。
逆にお聞きしたいのですが４行ともでしたらなぜ必要ではないと思われたのか教えてください。

2019-01-15 12:25 UTC, fukumotomasashi commented
修正しました。

2019-01-15 12:27 UTC, ReoKuriyama commented on app/controllers/users_controller.rb
> +      format.html
htmlレスポンスは使わないので5行めだけですね

2019-01-15 12:32 UTC, fukumotomasashi commented
再修正しました

2019-01-15 12:34 UTC, ReoKuriyama requested changes

2019-01-15 12:34 UTC, ReoKuriyama commented on app/assets/javascripts/user.js
> +  var removeUserList = $('#user-search-result2')
`#user-search-result2`これを実際に定義しているのであれば命名がふさわしくないです

2019-01-15 12:34 UTC, ReoKuriyama commented on app/assets/javascripts/user.js
> +          appendNoAddUserList("一致するユーザーはいません")
引数にして渡す必要はないかと思います。

2019-01-15 12:34 UTC, ReoKuriyama commented
コメント追加しましたので修正お願いします

2019-01-15 12:35 UTC, yusukeyamane commented on app/assets/javascripts/user.js
> +  $(function() {
$(function() {
の記述はこのファイルの最上部に書かれている一度だけで、ほかは不要だと思うのですがいかがでしょうか？

2019-01-15 12:35 UTC, yusukeyamane commented on app/assets/javascripts/user.js
> +  $(function() {
こちらも

2019-01-15 12:36 UTC, yusukeyamane commented on app/controllers/users_controller.rb
> +    respond_to do |format|
htmlを返す可能性がないのであればrespond_to do |format|という記述で繰り返しをする必要は無く
render :json
で良いと思います。

2019-01-15 12:37 UTC, yusukeyamane commented on Gemfile
> +# gem 'turbolinks', '~> 5'
コメントアウトするなら削除してしまって大丈夫です。（コメントアウトは基本的にメモの様な使い方をします。）

2019-01-16 03:31 UTC, fukumotomasashi commented
修正しました

2019-01-16 03:33 UTC, hzak2xx approved these changes
LGTMです

2019-01-16 03:39 UTC, merged